# Generated by Django 2.2.16 on 2022-11-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221117_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
    ]
