# Generated by Django 2.2.16 on 2022-11-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping_cart', to='recipes.Recipe'),
        ),
    ]
