# Generated by Django 2.2.16 on 2022-11-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221117_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
